# Generated by Django 6.0.5 on 2026-05-10 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extracted_text', models.TextField(blank=True)),
                ('skills_found', models.TextField(blank=True, default='[]')),
                ('ats_score', models.FloatField(default=0.0)),
                ('ats_breakdown', models.TextField(blank=True, default='{}')),
                ('ai_suggestions', models.TextField(blank=True)),
                ('interview_questions', models.TextField(blank=True, default='{}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
